# ============================================
# VietExplore-AI Production Dockerfile
# ============================================
# Multi-stage build optimized for Next.js 15 with standalone output
# Target image size: ~300-400MB (vs 1.6GB unoptimized)
# Build time: ~2-3 minutes with cache
#
# Usage:
#   docker build -t vietexplore-ai:latest .
#   docker run -p 3000:3000 --env-file .env.local vietexplore-ai:latest
#
# Security: Non-root user, minimal dependencies, Alpine Linux
# ============================================

# ============================================
# STAGE 1: Dependencies Installation
# ============================================
FROM node:20-alpine AS deps

# Install system dependencies for Sharp (image processing)
# libc6-compat: Compatibility layer for glibc-based binaries
# python3, make, g++: Build tools for native modules
RUN apk add --no-cache \
    libc6-compat \
    python3 \
    make \
    g++

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install production dependencies only
# --omit=dev: Skip devDependencies
# npm ci: Clean install (faster, reproducible)
RUN npm ci --omit=dev && \
    npm cache clean --force

# ============================================
# STAGE 2: Build Application
# ============================================
FROM node:20-alpine AS builder

# Install build dependencies
RUN apk add --no-cache \
    libc6-compat \
    python3 \
    make \
    g++

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install ALL dependencies (including devDependencies for build)
RUN npm ci && \
    npm cache clean --force

# Copy application source
COPY . .

# Build arguments for NEXT_PUBLIC_ environment variables
# These are embedded in the client-side bundle at build time
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_DATABASE_URL
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_CLARITY_PROJECT_ID
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_ENABLE_AI_FEATURES=false
ARG NEXT_PUBLIC_ENABLE_ANALYTICS=true
ARG SITE_URL

# Set environment variables for build
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_DATABASE_URL=$NEXT_PUBLIC_FIREBASE_DATABASE_URL
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_CLARITY_PROJECT_ID=$NEXT_PUBLIC_CLARITY_PROJECT_ID
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_ENABLE_AI_FEATURES=$NEXT_PUBLIC_ENABLE_AI_FEATURES
ENV NEXT_PUBLIC_ENABLE_ANALYTICS=$NEXT_PUBLIC_ENABLE_ANALYTICS
ENV SITE_URL=$SITE_URL
ENV NODE_ENV=production

# Build Next.js application
# Outputs:
#   - .next/standalone (minimal runtime)
#   - .next/static (static assets)
#   - public/ (unchanged)
# Postbuild: next-sitemap generates XML sitemaps
RUN npm run build

# ============================================
# STAGE 3: Production Runtime
# ============================================
FROM node:20-alpine AS runner

# Install runtime dependencies only
RUN apk add --no-cache \
    libc6-compat \
    curl

WORKDIR /app

# Create non-root user for security
# nextjs:nodejs (uid:gid = 1001:1001)
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Set production environment
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Copy production dependencies from deps stage
COPY --from=deps --chown=nextjs:nodejs /app/node_modules ./node_modules

# Copy built application from builder stage
# Standalone output includes all required dependencies
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Copy package.json for reference (version info, etc.)
COPY --chown=nextjs:nodejs package.json ./

# Switch to non-root user
USER nextjs

# Expose port
EXPOSE 3000

# Health check
# Checks if Next.js server is responding
# Interval: 30s, Timeout: 3s, Start period: 10s (allow startup time)
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
    CMD curl -f http://localhost:3000/api/health || exit 1

# Start Next.js production server
# server.js is generated by Next.js standalone build
CMD ["node", "server.js"]

# ============================================
# Build & Run Instructions
# ============================================
#
# 1. Build image:
#    docker build \
#      --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=your_key \
#      --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=your_domain \
#      ... (other NEXT_PUBLIC_ vars) \
#      -t vietexplore-ai:latest .
#
# 2. Run container:
#    docker run -d \
#      -p 3000:3000 \
#      -e FIREBASE_PROJECT_ID=your_project_id \
#      -e FIREBASE_CLIENT_EMAIL=your_email \
#      -e FIREBASE_PRIVATE_KEY="$(cat firebase-key.txt)" \
#      -e GOOGLE_AI_API_KEY=your_api_key \
#      -e CRON_SECRET=your_cron_secret \
#      -e NEXTAUTH_URL=http://localhost:3000 \
#      --name vietexplore-ai \
#      vietexplore-ai:latest
#
# 3. View logs:
#    docker logs -f vietexplore-ai
#
# 4. Stop container:
#    docker stop vietexplore-ai
#
# 5. Remove container:
#    docker rm vietexplore-ai
#
# ============================================
# Security Best Practices Applied
# ============================================
# ✅ Multi-stage build (no build tools in runtime)
# ✅ Non-root user (nextjs:nodejs)
# ✅ Alpine Linux (minimal attack surface)
# ✅ Health check enabled
# ✅ Minimal dependencies in production
# ✅ No secrets baked into image (via ARG/ENV at runtime)
# ✅ Build cache optimization (layer caching)
#
# ============================================
